/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#091007",
        "on-background": "#dde5d5",
        "inverse-on-surface": "#2b3228",
        "error-container": "#93000a",
        "surface-container": "#1b2117",
        "tertiary-fixed": "#e5e2e1",
        "surface-container-low": "#171d14",
        "on-tertiary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-fixed": "#022100",
        "secondary-fixed-dim": "#ffb3ad",
        "outline": "#889480",
        "on-secondary-container": "#ff9e97",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#970214",
        "primary": "#6ae050",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#86fd69",
        "on-surface-variant": "#becbb4",
        "on-tertiary": "#303030",
        "surface": "#0f150c",
        "on-secondary-fixed-variant": "#930012",
        "on-tertiary-container": "#2d2d2d",
        "secondary": "#ffb3ad",
        "outline-variant": "#3f4a39",
        "surface-container-high": "#252c21",
        "primary-fixed-dim": "#6ae050",
        "background": "#0f150c",
        "secondary-fixed": "#ffdad7",
        "on-secondary": "#68000a",
        "on-primary": "#053900",
        "on-error": "#690005",
        "inverse-surface": "#dde5d5",
        "error": "#ffb4ab",
        "tertiary-container": "#969494",
        "on-primary-container": "#043600",
        "surface-variant": "#30372c",
        "surface-bright": "#343b30",
        "on-surface": "#dde5d5",
        "surface-container-highest": "#30372c",
        "on-secondary-fixed": "#410004",
        "primary-container": "#34ab1e",
        "tertiary": "#c8c6c5",
        "inverse-primary": "#106e00",
        "surface-tint": "#6ae050",
        "surface-dim": "#0f150c",
        "on-primary-fixed-variant": "#095300",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        unit: "8px",
        "container-max": "1440px",
        gutter: "32px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        glow: "0px 20px 50px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
